<?php
namespace TaxCloud\Tests;

use TaxCloud\Address;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:51:27.
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Address
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->object = new Address(
        '1600 Pennsylvania Ave NW',
        '',
        'Washington',
        'DC',
        '20006',
        '0004'
      );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \TaxCloud\Address::getAddress2
     */
    public function testGetAddress2()
    {
        $address2 = $this->object->getAddress2();
        $this->assertEmpty($address2, 'Address2 should be empty.');
    }

    /**
     * @covers \TaxCloud\Address::setZip5
     */
    public function testSetZip5()
    {
        $this->object->setZip5('12345');
        $this->assertEquals('12345', $this->object->getZip5(), 'ZIP5 should be set to 12345.');
    }

    /**
     * @covers \TaxCloud\Address::setZip4
     */
    public function testSetZip4()
    {
        $this->object->setZip4('1234');
        $this->assertEquals('1234', $this->object->getZip4(), 'ZIP4 should be set to 1234.');
    }

    /**
     * @covers \TaxCloud\Address::getZip
     */
    public function testGetZip()
    {
      $zip = $this->object->getZip();
      $this->assertEquals('20006-0004', $zip, 'getZip() should return ZIP+4');
    }
}
