<?php

namespace TaxCloud\Tests;

use TaxCloud\CartItem;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:52:40.
 */
class CartItemTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CartItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->object = new CartItem(
        '123',
        'ABC123',
        '00000',
        '12.34',
        '1'
      );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /** @covers TaxCloud\CartItem::setPrice
     * @todo   Implement testSetPrice().
     */
    public function testSetPrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
